package paradot.mobilzeo.dto

class MobilePlanDto(
    val id: Int,
    val name: String,
    val price_initial: Int,
    val price_after_change: Int?,
    val initial_price_month: Int?,
    val data_per_month: Int,
    val data_per_day: Int?,
    val data_exhaustion_speed: Double?,
    val call_minutes: Int,
    val text_messages: Int,
    val main_carrier: String,
    val banners: List<String>,
    val view_count: Int,
    val usim_price: Int,
    val usim_nfc_price: Int?,
    val esim_price: Int?,
    val usim_subtitle: String,
    val usim_title: String,
    val usim_description: String?,
    val benefit: List<BenefitDto>,
    val youtube_url: String?,
    val ars_call_minutes: Int?,
    val carrier_app: String?,
    val hotspot_giga: Int?,
    val micropayments_months: Int?,
    val roaming_minutes: Int?,
    val internet_iptv: String?,
    val family_complimentary: String?,
    val data_sharing: String?,
    val priority: Int,
    val signup_auth: String?,
    val signup_minors: String?,
    val signup_foreigners: String?,
    val plan_exceed: String,
    val carrier: MobileCarrierDto,
    val cta_url: String
)